# Application
spring.application.name=tradeSphere
# Server
server.port=8080
# MongoDB
spring.data.mongodb.uri=mongodb+srv://tradesphere:New0ne890@cluster0.jdf136e.mongodb.net/tradesphere?appName=Cluster0
# JWT
jwt.secret=mySecretKeyForTradeSphereApplication12345678901234567890
jwt.access-token-expiration=60480000000
jwt.refresh-token-expiration=6048000

# Logging
logging.level.org.springframework.security=DEBUG

# File Upload Configuration
spring.servlet.multipart.enabled=true
# Maximum size of a single file
spring.servlet.multipart.max-file-size=20MB
# Maximum size of the complete request
spring.servlet.multipart.max-request-size=40MB

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000# APPLICATION CONFIGURATION



