# Application
spring.application.name=tradeSphere
# Server
server.port=8081
# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/tradeSphere
# JWT
jwt.secret=mySecretKeyForTradeSphereApplication12345678901234567890
jwt.expiration=3600000
# Logging
logging.level.org.springframework.security=DEBUG
# Jackson
spring.jackson.default-property-inclusion=non_null
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.verify.service.sid=${TWILIO_VERIFY_SERVICE_SID}