# Application
spring.application.name=tradeSphere
# Server
server.port=8080
# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/tradeSphere
# JWT
jwt.secret=mySecretKeyForTradeSphereApplication12345678901234567890
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
# Logging
logging.level.org.springframework.security=DEBUG
#mail
spring.mail.host=smtpout.secureserver.net
spring.mail.port=587
spring.mail.username=noreply@nutricafoods.com
spring.mail.password=YOUR_EMAIL_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000# APPLICATION CONFIGURATION
#app config
app.frontend-url=http://localhost:3000
app.verification.expiry-minutes=30
app.password-reset.expiry-minutes=15


