# Application
spring.application.name=tradeSphere
# Server
server.port=8080
# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/tradeSphere
# JWT
jwt.secret=mySecretKeyForTradeSphereApplication12345678901234567890
jwt.expiration=86400000
# Logging
logging.level.org.springframework.security=DEBUG
# Jackson
spring.jackson.default-property-inclusion=non_null